### ISSUE TITLE
Unknown Playlist function

### ISSUE THREAD

**Issue by drnic** [PineappleExpress808/lex-gpt#9]
In https://github.com/PineappleExpress808/lex-gpt/blob/6d0d2066efd176e0876ddab1419ac4e1e99bba80/scripts/get_data.ipynb#L66 there is a reference to `Playlist` - it isn't loaded earlier I think. Where can it be found? Thx.

**Comment by rlancemartin** [comment]
tx, just fixed. needs import of: from youtubesearchpython import *

**Comment by drnic** [comment]
Champion.
